### ISSUE TITLE
Get dynamic_reconfigure working properly

### ISSUE THREAD

**Issue by aruisdante** [RIVeR-Lab/kvh#10]
Currently even though dynamic_reconfigure is building properly, it doesn't seem to be actually registering with the system. We need to get dynamic_reconfigure working, and then add the appropriate functionality to allow for handling parameter adjustment.

**Comment by mitchellwills** [comment]
I wonder if catkin is doing something different

**Comment by mitchellwills** [comment]
@aruisdante I just tried this and dynamic reconfigure seems to be working fine. The parameters show up and the callback get called with new values. When I tried to compile the master branch there was a compiler error, but that was just because the dynamic reconfigure callback was missing the level argument. Do you have more to commit on your end or can I commit this fix?

**Comment by aruisdante** [comment]
@mitchellweb1 There was an update yesterday to a bunch of stuff in ROS and I think DR was one of the things updated. Maybe that fixed it. Go ahead and commit the fixes.
